# 10장 예외 처리

* 코루틴에서 잡히지 않은 예외가 발생했을 때 종료
* 코루틴 빌더는 부모도 종료 시키고, 취소된 부모는 자식도 모두 취소시킨다

```kotlin
fun main() = runBlocking { // 부모 - 자기 자신과 자식을 모두 취소하고 예외를 던짐
    launch { // 부모&자식 - 자기 자신과 자식을 취소하고 예외를 부모로 전파
        launch {
            delay(1000)
            throw Error("Some Error") // 자기 자신을 취소하고 예외를 부모로 전파
        }
        
        launch {
            delay(2000)
            println("Will not be printed")
        }
        
         launch {
            delay(500)
            println("Will be printed") // delay 짧음, 예외 발생 이전에 출력됨
        }
    }
    
    launch {
        delay(2000)
        println("Will not be printed")
    }
}

// Will be printed
// Exception in thread ....
```



## 코루틴 종료 멈추기

* 코루틴이 종료되기 전에 try-catch로 예외를 잡기는 어렵다;
  * 코루틴 간의 상호작용은 job을 통해서 일어나기때문에, 코루틴 빌더 내부에서 새로운 코루틴 빌더를 try-catch로 래핑하는 건 도움이 안됨

```kotlin
fun main() = runBlocking {
    // try-catch 문은 무시됨
    try {
        launch {
            delay(1000)
            throw Error("Some Error")
        }
    } catch (e: Throwable) { // 무시됨
        println("Will not be printed")
    }
    launch {
        delay(2000)
        println("Will not be printed")
    }
}
```

### SupervisorJob

자식에게 발생한 모든 예외 무시

* 일반적으로 다수의 코루틴을 시작하는 스코프로 사용된다

```kotlin
fun SupervisorJob(parent: Job? = null): CompletableJob
```

```kotlin
fun main() = runBlocking {
    val scope = CoroutineScope(SupervisorJob())
    scope.launch {
        delay(1000)
        throw Error("Some Error") // 에러를 부모에게 전파, 부모를 취소하려고 시도 (취소 안됨)
    }
    
    scope.launch {
        delay(2000)
        println("Will be printed") // 부모 취소되지 않으므로 출력
    }
    
    delay(3000)
}

// Exception...
// Will be printed
```

<figure><img src="../.gitbook/assets/스크린샷 2024-06-05 오전 8.04.17 (1).png" alt=""><figcaption></figcaption></figure>

* 같은 job을 다수의 코루틴 컨텍스트로 사용하는 것이 좀 더 나은 방식
  * 하나의 코루틴이 취소되어도 다른 코루틴이 취소 되지 않는다

```kotlin
fun main() = runBlocking {
    val job = SupervisorJob()
    launch(job) {
        delay(1000)
        throw Error("Some error")
    }

    launch(job) {
        delay(2000)
        println("will be printed")
    }
    job.join()
}

// (1초 후)
// Exeption...
// (2초 후)
// Will be printed
```

#### 주의!

Supervisorjob을 부모 코루틴의 인자로 사용하지 말 것

* 아래처럼 사용할 경우 SupervisorJob은 단 하나의 자식만 가지기 때문에, 예외처리에 도움이 안됨

```kotlin
// 이렇게 하면 안됨
fun main() = runBlocking {
        launch(SupervisorJob()) { // 이렇게 하지 말기! 
            launch {
                delay(1000)
                throw Exception("error")
            }
            launch {
                delay(2000)
                println("will be printed")
            }
        }
        delay(3000)
    }
}

// Exception in thread "main" java.lang.Exception: error
```



{% embed url="https://stackoverflow.com/questions/74985633/coroutinescope-with-supervisorjob-vs-supervisorscope" %}

<figure><img src="../.gitbook/assets/스크린샷 2024-06-05 오전 8.33.06.png" alt=""><figcaption></figcaption></figure>

### supervisorScope

코루틴 빌더를 supervisorScope 로 래핑하기

* 다른 코루틴에서 발생한 예외를 무시하고 부모와의 연결을 유지한다
* supervisorScope는 중단 함수
* 일반적인 사용 방법은 서로 무관한 다수의 작업을 스코프 내에서 실행하는 것

```kotlin
public suspend fun <R> supervisorScope(block: suspend CoroutineScope.() -> R): R {
    contract {
        callsInPlace(block, InvocationKind.EXACTLY_ONCE)
    }
    return suspendCoroutineUninterceptedOrReturn { uCont ->
        // SupervisorJob의 속성을 가지고 있는 CoroutineScope?
        val coroutine = SupervisorCoroutine(uCont.context, uCont)
        coroutine.startUndispatchedOrReturn(coroutine, block)
    }
}
```

```kotlin
fun main(): Unit = runBlocking {
    supervisorScope { // 예외 무시
        launch {
            delay(1000)
            throw Error("Some error") // 예외 발생
        }

        launch {
            delay(2000)
            println("will be printed") // 예외 무시하고 부모와 연결 유지
        }
    }
    delay(1000)
    println("Done")
}

// Exception...
// Will be printed
// (1초 후)
// Done
```



#### 주의!

supervisorScope 는 withContext(SupervisorJob())으로 대체될 수 없다!

* SupervisorJob이 withContext의 부모가 됨 > 자식 코루틴 예외가 발생하면 withContext 코루틴으로 전달되며 job이 취소 > 자식 코루틴도 모두 취소됨

```kotlin
// 이렇게 하면 안됨
suspend fun sendNotificatoins(notifications: List<Notification>)
    = withContext(SupervisorJob()) {
        for (notification in notifications) {
            launch {
                client.send(notification)
            }
        }
    }
```

### await

```kotlin
class MyException: Throwable()

suspend fun main() = supervisorScope { // 예외 무시
        val str1 = async<String> {
            delay(1000)
            throw MyException() // 예외 발생, 부모코루틴을 종료하고 다른 코루틴도 종료시키려고 함
        }
        val str2 = async {
            delay(2000)
            "Text2"
        }
        
        try {
            println(str1.await()) // 예외로 종료되어 반환할 값이 없지만, MyException을 던짐 
        } catch (e: Throwable) {
            println(e) // MyException 출력
        }
        
        println(str2.await()) // 예외 무시, 취소되지 않고 실행됨
    }
}

// MyException
// Text2
```



## CancellationException은 부모까지 전파되지 않는다

* 예외가 CancellationException의 서브클래스라면 부모로 전파되지 않고 현재 코루틴만 취소함

```kotlin
public class CancellationException extends IllegalStateException {
    private static final long serialVersionUID = -9202173006928992231L;

    public CancellationException() {}
    public CancellationException(String message) {
        super(message);
    }
}
```

* 다른 클래스나 객체로 확장될 수 있음

```kotlin
object MyNonPropagatingException: CancellationException() // 커스텀? 예외

suspend fun main() = coroutineScope {
    launch {
        launch {
            delay(2000)
            println("Will not be printed")
        }
        throw MyNonPropagatingException
    }
    
    launch {
        delay(2000)
        println("Will be printed") // 부모까지 예외 전파되지 않으므로 출력됨
    }
}

// (2초 후)
// Will be printed
```



## 코루틴 예외 핸들러 - CoroutineExceptionHandler 컨텍스트

* 예외 전파를 중단시키지는 않지만, 예외가 발생했을 때 해야할 것들을 정의하는 데 사용
  * ex) 예외 스택 트레이스 출력, 에러 메시지 노출

```kotlin
fun main() = runBlocking {
    val handler = CoroutineExceptionHandler { ctx, exception -> 
        println("Caught $exception")
    }
    
    val scope = CoroutineScope(SupervisorJob() + handler)
    scope.launch {
        delay(1000)
        throw Error("Some error")
    }
    
    scope.launch {
        delay(2000)
        println("Will be printed") // 부모까지 예외 전파되지 않으므로 출력됨
    }
    
    delay(3000)
}

// Caught java.lang.Error : Some Error
// Will beprintted
```

