# 11장 코루틴 스코프 함수

여러 개의 엔드포인트에서 데이터를 동시에 얻어야 하는 중단함수는 어떻게 구현해야할까?

## 코루틴 스코프 소개 이전에 사용한 방법들

#### 방법 1) 중단 함수에서 중단함수 호출하기

* 문제 - 작업이 동시에 진행되지 않으므로 1초 + 1초 = 2초나 걸림

```kotlin
suspend fun getUserProfile(): UserProfileData {
    val user = getUserData()                // (1초 후)
    val notifications = getNotifications() // (1초 후)
    
    return UserProfileData(
        user = user,
        notifications = notifications
    )
}
```

#### 방법 2) 동시 작업을 위해 async 로 래핑하기

`async` 는 스코프내에서 호출되어야 한다,, 하지만 그렇다고 `GlobalScope`를 사용하면 안된다

```kotlin
// 이렇게 구현하면 안돼!
suspend fun getUserProfile(): UserProfileData {
    val user = GlobalScope.async { getUserData() }              
    val notifications = GlobalScope.async { getNotifications() }
    
    return UserProfileData(
        user = user.await(),
        notifications = notifications.await()
    )
}
```

GlobalScope는 EmptyCoroutineContext를 가진 스코프 일 뿐이므로, 내부에서 async를 호출하면 몇몇 문제가 생길 수 있다

* 문제
  * async가 부모 코루틴과 아무런 관계가 없어지므로 취소될 수 없다 (부모가 취소되어도 async 내부 함수는 여전히 실행 중인 상태가 됨)
  * 부모 코루틴으로부터 스코프를 상속받지 않고 기본 디스패처에서 실행되며, 부모의 컨텍스트와 전혀 연관이 없다
  * 즉, 메모리 누수가 발생할 수 있고 & 테스트하기도 어려워진다

```kotlin
public object GlobalScope : CoroutineScope {
    override val coroutineContext: CoroutineContext
        get() = EmptyCoroutineContext
}

public object EmptyCoroutineContext : CoroutineContext, Serializable {
    private const val serialVersionUID: Long = 0
    private fun readResolve(): Any = EmptyCoroutineContext

    public override fun <E : Element> get(key: Key<E>): E? = null
    public override fun <R> fold(initial: R, operation: (R, Element) -> R): R = initial
    public override fun plus(context: CoroutineContext): CoroutineContext = context
    public override fun minusKey(key: Key<*>): CoroutineContext = this
    public override fun hashCode(): Int = 0
    public override fun toString(): String = "EmptyCoroutineContext"
}
```

#### 방법 3) 스코프를 인자로 넘기기

* 장점 - 취소가 가능하고 적절한 단위 테스트를 추가할 수 있다
* 문제 - 스코프가 함수에서 함수로 전달되면서 예상하지 못한 부작용이 발생할 수 있다,,, 잠재적으로 위험!
  * async에서 예외가 발생하면 모든 스코프가 닫힐 수도 있음 (SupervisorJob이 아닌 경우)
  * 스코프에 접근하는 함수가 cancel 메서드로 스코프를 취소하는 등 스코프를 조작할 수도 있음

```kotlin
// 이렇게 구현하면 안돼!
suspend fun getUserProfile(
    scope: CoroutineScope
): UserProfileData {
    val user = scope.async { getUserData() }              
    val notifications = scope.async { getNotifications() }
    
    return UserProfileData(
        user = user.await(),
        notifications = notifications.await()
    )
}

// 이것도 안돼!
suspend fun CoroutineScope.getUserProfile(): UserProfileData {
    val user = async { getUserData() }              
    val notifications = async { getNotifications() }
    
    return UserProfileData(
        user = user.await(),
        notifications = notifications.await()
    )
}
```

* 잘못 구현한 예제

```kotlin
data class Details(val name: String, val followers: Int)
data class Tweet(val text: String)

fun getFollowersNumber(): Int =
    throw Error("Service exception")
    
suspend fun getUserName(): String {
    delay(500)
    return "chaeeun"
}

suspend fun getTweets(): List<Tweet> {
    return listOf(Tweet("Hello, world"))
}

// 잘못된 구현 방법!
// Ambiguous coroutineContext due to CoroutineScope receiver of suspend function 
suspend fun CoroutineScope.getUserDetails(): Details {
    val userName = async { getUserName() }
    val followersNumber = async { getFollowersNumber() }
    return Details(userName.await(), followersNumber.await())
}

fun main() = runBlocking {
    val details = try {
        getUserDetails() // 발생한 예외가 해당 async를 종료, 전체 스코프 종료로 이어짐
    } catch (e: Error) {
        null
    }
    
    val tweets = async { getTweets() } // 전체 스코프 종료되어 동작 안함
    println("User: $details")
    println("Tweets: ${tweets.await()}")
}

// 예외만 발생
```

## coroutineScope

스코프를 시작하는 중단 함수, 인자로 들어온 함수가 생성한 값을 반환한다

```kotlin
suspend fun <R> coroutineScope(block: suspend CoroutineScope.() -> R): R
```

* async나 launch와 다르게 coroutineScope의 본체는 리시버없이 곧바로 호출됨
* 새로운 코루틴을 생성, 새로운 코루틴이 끝날 때 까지 coroutineScope를 호출한 코루틴을 중단한다
  * 기존의 중단 컨텍스트에서 벗어난 새로운 스코프 > 부모로부터 상속받고 구조화된 동시성을 지
* 생성된 스코프는 바깥의 스코프에서 coroutineContext를 상속받지만, 컨텍스트의 Job을 오버라이딩한다
  * 부모로 부터 컨텍스트를 상속받음
  * 자신의 작업을 끝내기 전까지 모든 자식을 기다림
  * 부모가 취소되면 자식들 모두를 취소함

```kotlin
fun main() = runBlocking {   
    val a = coroutineScope { 
        delay(1000)
        10
    }
    println("a is caculated")
    val b = coroutineScope {
        delay(1000)
        20
    }
    println(a) // 10
    println(b) // 20
}

// (1초 후)
// a is calculated
// (1초 후)
// 10
// 20
```

#### coroutineContext가 상속되고, coroutineScope는 모든 자식이 끝날 때까지 종료되지 않는다

```kotlin
suspend fun longTask() = coroutineScope {
    launch {
        delay(1000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 1")
    }
    
    launch {
        delay(2000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 2")
    }
}

fun main() = runBlocking(CoroutineName("Parent")) {
    println("Before")
    longTask() // coroutineScope를 호출한 코루틴은 중단되므로, 작업이 끝나고 나서야 After 출력됨
    println("After")
}

// Before
// (1초 후)
// [Parent] Finished task 1
// (1초 후)
// [Parent] Finished task 2
// After
```

#### 부모가 취소되면 아직 끝나지 않은 자식 코루틴도 전부 취소됨

```kotlin
suspend fun longTask() = coroutineScope {
    launch {
        delay(1000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 1")
    }
    
    launch {
        delay(2000)
        val name = coroutineContext[CoroutineName]?.name
        println("[$name] Finished task 2")
    }
}

fun main() = runBlocking {
    val job = launch(CoroutineName("Parent")) {
        longTask()
    }
    delay(1500)
    job.cancel() // 부모 취소
}

// [Parent] Finished task 1
```

#### 코루틴 빌더와 달리 coroutineScope나 스코프에 속한 자식에서 예외가 발생하면, 다른 모든 자식이 취소되고 예외가 다시 던져진다

```kotlin
data class Details(val name: String, val followers: Int)
data class Tweet(val text: String)

fun getFollowersNumber(): Int =
    throw Error("Service exception")
    
suspend fun getUserName(): String {
    delay(500)
    return "chaeeun"
}

suspend fun getTweets(): List<Tweet> {
    return listOf(Tweet("Hello, world"))
}

// 위 잘못된 구현 예시의 해결 방법
suspend fun getUserDetails(): Details = coroutineScope {
    val userName = async { getUserName() } // 예외 발생, 해당 스코프에 속한 자식들 모두 취소, 예외 다시 던져짐
    val followersNumber = async { getFollowersNumber() } // 취소됨
    return@coroutineScope Details(userName.await(), followersNumber.await())
    // return@ - https://kotlinlang.org/docs/returns.html
}

fun main() = runBlocking {
    val details = try {
        getUserDetails()
    } catch (e: Error) {
        println("Error : $e")
        null
    }
    
    val tweets = async { getTweets() }
    println("User: $details")
    println("Tweets: ${tweets.await()}")
}

// Error : java.lang.Error: Service exception
// User: null
// Tweets: [Tweet(text=Hello, world)]
```

#### 병렬 작업 수행&#x20;

```kotlin
suspend fun getUserProfile(): UserProfileData = 
    coroutineScope {
        val user = async { getUserData() }
        val notifications = async { getNotifications() }
        
        UserProfileData(
            user = user.await(),
            notifications = notifications.await()
        )
    }
```

#### 중단 메인 함수를 래핑할 때 주로 사용됨 (runBlocking 대신!)

```kotlin
suspend fun main() = coroutineScope {
    launch {
        delay(1000)
        println("World")
    }
    println("Hello,")
}

// Hello,
// (1초 후)
// World
```

## 코루틴 스코프 함수

중단 함수에서 코루틴 스코프를 만들기 위해 사용하는 중단 함수로, 람다식 전체를 래핑할 때 주로 사용한다

| 코루틴 빌더 (runBlocking 제외)          | 코루틴 스코프 함수                                                   |
| -------------------------------- | ------------------------------------------------------------ |
| launch / async / produce         | coroutineScope / supervisorScope / withContext / withTimeout |
| CoroutineScope의 확장 함수            | 중단 함수                                                        |
| CoroutineScope 리시버의 코루틴 컨텍스트를 사용 | 중단 함수의 Continuation 객체가 가진 코루틴 컨텍스트를 사용                      |
| 예외는 Job을 통해 부모로 전파됨              | 일반 함수와 같은 방식으로 예외를 던짐                                        |
| 비동기인 코루틴을 시작함                    | 코루틴 빌더가 호출된 곳에서 코루틴을 시작함                                     |

* runBlocking은 특수한 코루틴 빌더로, 코루틴 계층 중 가장 상위에 있는 블로킹 함수 (코루틴 스코프는 계층 중간)

### withContext

coroutineScope와 비슷 BUT 스코프의 컨텍스트를 변경할 수 있다

* withContext의 인자로 컨텍스트를 제공하면 코루틴 빌더와 같은 방식으로, 부모 스코프의 컨텍스트를 대체한다

```kotlin
fun CoroutineScope.log(text: String) {
    val name = this.coroutineContext[CoroutineName]?.name
    println("[$name] $text")
}

fun main() = runBlocking(CoroutineName("Parent")) {
    log("Before")
    
    withContext(CoroutineName("Child1")) { // 컨텍스트 변경
        delay(1000)
        log("Hello 1")
    }
    
    withContext(CoroutineName("Child2")) { // 컨텍스트 변경
        delay(1000)
        log("Hello 2")
    }
    
    log("After")
}

// [Parent] Before
// (1초 후)
// [Child1] Hello 1
// (1초 후)
// [Child2] Hello 2
// [Parent] After
```

* 기존 스코프와 컨텍스트가 다른 코루틴 스코프를 설정하기 위해 주로 사용된다(w. 디스패처Dispatchers)

```kotlin
launch(Dispatchers.Main) {
    view.showProgressBar()
    withContext(Dispatchers.IO) {
        fileRepository.saveData(data)
    }
    view.hideProgressBar()
}
```

### supervisorScope

Job을 SupervisorJob으로 오버라이딩한 coroutineScope

#### 자식 코루틴이 예외를 던지더라도 취소되지 않는다

```kotlin
fun main() = runBlocking {
    println("Before")
    
    supervisorScope {
        launch {
            delay(1000)
            throw Error() // 예외 발생, 부모에게 예외 전파 취소 > supervisorScope라 전파 안됨
        }
        
        launch {
            delay(2000)
            println("Done")
        }
    }
    
    println("After")
}

// Before
// (1초 후)
// 예외 발생
// (1초 후)
// Done
// After
```

#### 서로 독립적인 작업을 시작하는 함수에서 주로 사용함

```kotlin
suspend fun notifyAnanlytics(actions: List<UserAction>) = 
    supervisorScope {
        actions.forEach { action ->
            launch {
                notifyAnalytics(action) // ? 재귀 ?
            }
        }
    }
```

#### async를 사용할 경우, 예외가 부모로 전파되는 것을 막는 것 외에 추가적인 예외 처리가 필요하다

```kotlin
class ArticlesRepositoryComposite(
    private val articleRepositories: List<ArticleRepository>
): ArticeRepository {
    override suspend fun fetchArticles(): List<Article> = 
        supervisorScope {
            articleRepositories
                .map { async { it.fetchArticles() } }
                .mapNotNull {
                    try {
                        it.await() // await 호출을 try-catch로 래핑해서 예외를 처리
                    } catch (e: Throwable) {
                        e.printStackTrace()
                        null
                    }
                }
                .flatten()
                .sortedByDescending { it.publishedAt }
        }
}
```

#### withContext(SupervisorJob()) 사용하지 않기!!

* withContext는 여전히 기존에 가지고 있던 Job을 사용하고, SupervisorJob()이 해당 Job의 부모가 됨 > 따라서 SupervisorJob의 자식은 withContext Job 하나만 해당
* withContext 내 자식 코루틴의 부모는 SupervisorJob이 아닌 셈이 되므로, 예외가 발생했을 때 다른 코루틴에도 예외가 전파되어 취소됨

```kotlin
fun main() = runBlocking {
    println("Before")
    
    withContext(SupervisorJob()) {
        launch {
            delay(1000)
            throw Error
        }
        
        launch {
            delay(2000)
            println("Done")
        }
    }
    
    println("After")
}

// Before
// (1초 후)
// After
```

### withTimeout

timeout 값을 인자로 받는 coroutineScope

#### 실행이 너무 오래 걸리면 람다식은 취소되고, `TimeoutCancellationException`을 던진다

```kotlin
suspend fun test() = withTimeout(1500) {
    delay(1000)
    println("Still thinking,,,")
    delay(1000)
    println("Done!")
    42
}

suspend fun main() = coroutineScope {
    try {
        test() // withTimeout 제한 시간을 넘겨서 예외 던짐
    } catch (e: TimeoutCancellationException) {
        println("Cancelled")
    }
    delay(1000) // ? test()가 취소되었기 때문에 타임아웃 시간을 늘려도 아무런 도움 안됨
}

// (1초 후)
// Still thinking,,,
// (0.5초 후)
// Cancelled
```

#### 테스트할 때 유용

> runTest
>
> [https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html)
>
> ```kotlin
> dependencies {
>     testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutines_version"
> }
> ```

```kotlin
class CoroutineTest {
    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun testTime2() = runTest {
        withTimeout(1000) {
            delay(900) // runTest 내부에서는 가상 시간으로 작동 (실제로 900ms기다리지는 않음)
        }
    }

    @OptIn(ExperimentalCoroutinesApi::class)
    @Test(expected = TimeoutCancellationException::class)
    fun testTime1() = runTest {
        withTimeout(1000) {
            delay(1100)
        }
    }

    @Test
    fun testTime3() = runBlocking {
        withTimeout(1000) {
            delay(900) // 실제로 900ms 기다림
        }
    }
}
```

#### TimeoutCancellationException 예외는 부모에게 영향을 주지 않음

* TimeoutCancellationException은 CancellatinException의 서브타입
* 예외가 CancellationException의 서브클래스라면 부모로 전파되지 않고 현재 코루틴만 취소한다 (10장 예외 처리 참고)

```kotlin
suspend fun main() = coroutineScope {
    launch { // 취소됨
        launch { // 부모에 의해 취소됨
            delay(2000)
            println("will not be printed")
        }
        
        withTimeout(1000) {
            delay(1500) // 제한 시간보다 오래걸리므로 예외 던짐
        }
    }
    
    launch { // 영향 없음
        delay(2000)
        println("Done")
    }
}

// (2초 후)
// Done
```

#### withTimeoutOrNull

예외 대신 null을 반환

```kotlin
suspend fun fetchUser(): User {
    // 영원히 실행됨
    while(true) {
        yield()
    }
}

suspend fun getUserOrNull(): User? = 
    withTimeoutOrNull(5000) { // 응답이 5초 초과로 기다리면 Null 반환
        fetchUser()
    }
    
suspend fun main() = coroutineScope {
    val user = getUserOrNull()
    println("User: $user")
}
```

## 코루틴 스코프 함수 연결하기

서로 다른 코루틴 스코프 함수의 기능이 필요할 때, 코루틴 스코프 함수에서 다른 기능을 가진 코루틴 스코프 함수를 호출하면 된다!

```kotlin
suspend fun calculateAnswerOrNull(): User? = 
    withContext(Dispatchers.Default) {
        withTimeoutOrNull(1000) {
            calculateAnswer()
        }
    }
```

## 추가적인 연산&#x20;

작업을 수행하는 도중에 추가적인 연산을 수행하는 경우, 동일 스코프에서 launch를 호출하는 방법이 자주 사용된다

예) 사용자 프로필을 보여준 다음, 분석을 위한 목적으로 요청을 보내고 싶다면?

#### 잘못된 방법!

* coroutineScope가 사용자 데이터를 보여준 후, launch 로 시작된 코루틴이 끝나기를 기다려야 한다
* getProfile에서 예외가 발생하면, getName과 getFriends 요청도 취소되어야 하지만, 분석을 위한 호출이 실패했다고 전체 과정이 취소되는 건 원하지 않는 동작

```kotlin
class ShowUserDataUseCase(
    private val repo: UserDataRepository,
    private val view: UserDataView
) {
    suspend fun showUserData() = coroutineScope {
        val name = async { repo.getName() }
        val friends = async { repo.getFriends() }
        val profile = async { repo.getProfile() }
        val user = User(
            name = name.await(),
            friends = friends.await(),
            profile = profile.await()
        )
        
        view.show(user)
        launch { repo.notifyProfileShown() } // ?분석?
    }
}

fun onCreate() {
    viewModelScope.launch {
        _progressBar.value = true
        showUserData()
        _progressBar.value = false
    }
}
```

#### 또 다른 스코프에서 다른 동작을 시작하자

* 생성자를 통해 주입하면 유닛 테스트도 추가할 수 있고, 스코프를 사용하는데도 용이
* 중단 함수는 주입된 스코프에서 시작한 연산이 끝날 때 까지 기다리지 않음 (별도의 부모-자식 관계를 가지니까?)

🤔 스코프를 인자로 넘기지 말라고 위에 되어 있었는데

* 부모 역할을 할 스코프를 인자로 넘기지 말라는 건가? 흠

```kotlin
val analyticsScope = CoroutineScope(SupervisorJob())

class ShowUserDataUseCase(
    private val repo: UserDataRepository,
    private val view: UserDataView,
    private val analyticsScope: CoroutineScope // 생성자를 통해서 주입
) {
    suspend fun showUserData = coroutineScope {
        val name = async { repo.getName() }
        val friends = async { repo.getFriends() }
        val profile = async { repo.getProfile() }
        val user = User(
            name = name.await(),
            friends = friends.await(),
            profile = profile.await()
        )
        
        view.show(user)
        analyticsScope.launch { repo.notifyProfileShown() } // 주입된 스코프에서 추가적 연산 시작
    }
}
```
